#!/usr/bin/env python3
"""Build and validate data/registry.json for awesome-google-ads-mcp."""

import json
import os
import jsonschema

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")

taxonomy_defs = [
    {
        "id": "gaql-reporting",
        "number": 1,
        "name": "Query and report with GAQL",
        "slug": "1-query-and-report-with-gaql",
        "description": "High-throughput SearchStream pipelines, dynamic schema reflection, and lightweight proxies for executing GAQL queries.",
        "subcategories": [
            {
                "name": "Official DevRel gateways and gRPC SearchStream pipelines",
                "slug": "official-devrel-gateways-and-grpc-searchstream-pipelines",
                "description": "Official Google implementations and high-throughput gRPC streaming servers with full protobuf serialization.",
                "tool_slugs": ["googleads-google-ads-mcp", "binarcode-google-ads-mcp-http"]
            },
            {
                "name": "Dynamic schema reflection and field discovery",
                "slug": "dynamic-schema-reflection-and-field-discovery",
                "description": "Minimalist reflection servers querying GoogleAdsFieldService at runtime to eliminate schema drift and token bloat.",
                "tool_slugs": ["thainajardim-google-ads-mcp", "davidmosiah-google-ads-mcp-unofficial", "yeswanthreddyk-google-ads-mcp"]
            },
            {
                "name": "Zero-SDK lean REST and minimal GAQL execution",
                "slug": "zero-sdk-lean-rest-and-minimal-gaql-execution",
                "description": "Lightweight proxies bypassing heavy SDK binaries in favor of direct HTTP calls, raw JSON, and compact GAQL responses.",
                "tool_slugs": ["cohnen-mcp-google-ads", "x777-mcp-google-ads", "afzalalisolangi-googleads-mcp-server", "minholi-google-ads-mcp"]
            },
            {
                "name": "Edge runtimes and compiled native proxies",
                "slug": "edge-runtimes-and-compiled-native-proxies",
                "description": "Compiled Rust and high-performance TypeScript servers designed for serverless, low-memory, and edge execution.",
                "tool_slugs": ["fgribreau-mcp-google-ads", "lazare-42-google-ads-mcp", "kiarashedraki-google-ads-mcp", "cristiandrei1234-google-ads-mcp"]
            }
        ]
    },
    {
        "id": "local-persistence",
        "number": 2,
        "name": "Persist data locally and query with SQL",
        "slug": "2-persist-data-locally-and-query-with-sql",
        "description": "Embedded SQLite databases and background ingestion workers enabling sub-5ms SQL analytics with zero API quota consumption.",
        "subcategories": [
            {
                "name": "Embedded SQLite data warehouses with background workers",
                "slug": "embedded-sqlite-data-warehouses-with-background-workers",
                "description": "Meta-MCP architectures running local SQLite WAL engines that synchronize account telemetry and execute multi-table joins.",
                "tool_slugs": ["klosk-adloop", "akelaonline-mcp-google-ads"]
            },
            {
                "name": "Local campaign snapshot and zero-quota analytical caches",
                "slug": "local-campaign-snapshot-and-zero-quota-analytical-caches",
                "description": "Cached snapshot proxies enabling offline analytical queries and historical performance reporting without API rate limits.",
                "tool_slugs": ["atlasbarinc-google-ads-mcp", "mharnett-mcp-google-ads", "lucassantana-dev-google-ads-mcp"]
            }
        ]
    },
    {
        "id": "campaign-mutations",
        "number": 3,
        "name": "Automate campaign mutations, budgets, and bid strategies",
        "slug": "3-automate-campaign-mutations-budgets-and-bid-strategies",
        "description": "Tools capable of modifying live accounts—adjusting budgets, pausing ad groups, applying recommendations, and managing keyword lists.",
        "subcategories": [
            {
                "name": "Direct REST campaign mutation and bid/budget setters",
                "slug": "direct-rest-campaign-mutation-and-bidbudget-setters",
                "description": "Servers providing direct write endpoints for modifying campaign budgets, pausing ad groups, and adjusting bid amounts.",
                "tool_slugs": ["saifshabsug-google-ads-mcp-pro", "grantweston-google-ads-mcp-complete", "promobase-google-ads-mcp"]
            },
            {
                "name": "Validated campaign CRUD with dry-run mutation guards",
                "slug": "validated-campaign-crud-with-dry-run-mutation-guards",
                "description": "Mutation suites enforcing validate_only dry-run preflights and parameter checks before committing live changes.",
                "tool_slugs": ["epave-google-ads-mcp", "rgellis-google-ads-mcp", "abdulrhmanalhur-google-ads-mcp", "matheusslg-google-ads-mcp"]
            },
            {
                "name": "Keyword Planner and RLSA audience targeting suites",
                "slug": "keyword-planner-and-rlsa-audience-targeting-suites",
                "description": "Specialized keyword generation, negative keyword list management, and audience targeting automation tools.",
                "tool_slugs": ["konradbachowski-google-ads-mcp", "growmedevelopment-google-ads-mcp", "ball2jh-google-ads-mcp"]
            }
        ]
    },
    {
        "id": "mutation-safety-ui",
        "number": 4,
        "name": "Enforce mutation safety with visual MCP Apps and human approval",
        "slug": "4-enforce-mutation-safety-with-visual-mcp-apps-and-human-approval",
        "description": "Interactive React widgets, spend sliders, and window.postMessage protocols that physically bypass the LLM on financial commit.",
        "subcategories": [
            {
                "name": "Interactive React widgets with window.postMessage commit bypass",
                "slug": "interactive-react-widgets-with-windowpostmessage-commit-bypass",
                "description": "Implementations of @modelcontextprotocol/ext-apps rendering sandboxed webviews for human approval before spend execution.",
                "tool_slugs": ["nowork-studio-notfair-plugin", "ameydabhade-google-ads-mcp"]
            },
            {
                "name": "Spend protection sliders and physical budget modals",
                "slug": "spend-protection-sliders-and-physical-budget-modals",
                "description": "UI components featuring spend-cap sliders and visual guardrails to protect against accidental prompt-injection mutations.",
                "tool_slugs": ["monsieurgoodmood-google-ads-mcp-plus", "locomotive-agency-google-ads-mcp"]
            }
        ]
    },
    {
        "id": "agency-mcc",
        "number": 5,
        "name": "Manage agency access and multi-account MCC hierarchies",
        "slug": "5-manage-agency-access-and-multi-account-mcc-hierarchies",
        "description": "Manager Account (MCC) hierarchies, multi-client routing, 60-minute OAuth token refresh daemons, and credential vaults.",
        "subcategories": [
            {
                "name": "Dynamic MCC switching via login-customer-id routing",
                "slug": "dynamic-mcc-switching-via-login-customer-id-routing",
                "description": "Servers enabling agency operators to seamlessly switch between hundreds of client accounts by injecting login-customer-id headers.",
                "tool_slugs": ["noordevtech-googleads-mcp", "trueclicks-google-ads-mcp-js", "connorcallison-google-ads-mcp"]
            },
            {
                "name": "Proactive 60-minute OAuth token refresh daemons",
                "slug": "proactive-60-minute-oauth-token-refresh-daemons",
                "description": "Implementations that prevent the standard 3,600s Google OAuth session drop by running proactive background refresh loops.",
                "tool_slugs": ["gomarble-ai-google-ads-mcp-server", "connorstearns-mcp-google-ads", "johnoconnor0-google-ads-mcp"]
            },
            {
                "name": "Multi-tenant credential vaults and agency proxies",
                "slug": "multi-tenant-credential-vaults-and-agency-proxies",
                "description": "Secure multi-client credential isolation and agency gateway proxies designed for enterprise PPC operations.",
                "tool_slugs": ["dhawalshah-google-ads-mcp", "abhibavishi-google-ads-mcp", "shivpanks19-mcp-google-ads", "videngrowth-public-google-ads-mcp"]
            }
        ]
    },
    {
        "id": "domain-playbooks",
        "number": 6,
        "name": "Analyze performance with domain playbooks and heuristics",
        "slug": "6-analyze-performance-with-domain-playbooks-and-heuristics",
        "description": "AdTech domain reasoning engines enforcing conversion lag discounting, lost impression share attribution, and currency micros math.",
        "subcategories": [
            {
                "name": "Expert AdTech reasoning engines and conversion lag discounting",
                "slug": "expert-adtech-reasoning-engines-and-conversion-lag-discounting",
                "description": "Cognitive analytical engines embedding domain playbooks for 7-day conversion lag discounting and Bid-to-Position heuristics.",
                "tool_slugs": ["mathiaschu-google-ads-analyzer"]
            },
            {
                "name": "Impression share lost-to-budget and micros currency models",
                "slug": "impression-share-lost-to-budget-and-micros-currency-models",
                "description": "Specialized math helpers converting between raw micros ($1 = 1,000,000) and auditing Lost IS (budget) versus Lost IS (rank).",
                "tool_slugs": ["brandonmiller18-google-ads-mcp", "alexeykozyavkin-google-ads-mcp", "codyp10-google-ads-mcp"]
            }
        ]
    },
    {
        "id": "marketing-stacks",
        "number": 7,
        "name": "Integrate agentic workflows and multi-platform marketing stacks",
        "slug": "7-integrate-agentic-workflows-and-multi-platform-marketing-stacks",
        "description": "Autonomous Claude Code marketing skills, CLI copilot environments, and unified Google Ads + Meta Ads + GA4 growth platforms.",
        "subcategories": [
            {
                "name": "Autonomous Claude Code marketing skills and CLI copilots",
                "slug": "autonomous-claude-code-marketing-skills-and-cli-copilots",
                "description": "Ready-to-run Claude Code agent skills and terminal harnesses that execute ad audits and copy generation directly in CLI.",
                "tool_slugs": ["thatrebeccarae-claude-marketing", "themattberman-google-ads-copilot", "irinabuht12-oss-marketing-skills"]
            },
            {
                "name": "Unified Google Ads, Meta Ads, and GA4 analytics bridges",
                "slug": "unified-google-ads-meta-ads-and-ga4-analytics-bridges",
                "description": "Multi-channel marketing suites bridging Google Ads performance data with Meta Ads and Google Analytics 4 telemetry.",
                "tool_slugs": ["irinabuht12-oss-google-meta-ads-ga4-mcp", "itallstartedwithaidea-google-ads-mcp", "iflow-mcp-itallstartedwithaidea-google-ads-mcp", "zelentsov-dev-google-ads-mcp", "huzaifa-hb-google-ads-mcp", "mailmanar-google-ads-mcp"]
            }
        ]
    }
]

tools_data = {
    "googleads-google-ads-mcp": {
        "repo": "googleads/google-ads-mcp",
        "desc": "Official Google DevRel reference server featuring high-throughput gRPC SearchStream pipelines, complete protobuf serialization, and validate_only dry-run safety. Ideal for enterprise production gateways requiring direct alignment with upstream Google Ads API releases.",
        "role": "DevRel Gateway",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": True,
        "dry_run": True,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": True,
        "offline_conversions": False,
        "gaql_reflection": True,
        "sqlite_wal_cache": True,
        "query_latency": "Sub-5ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": True,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": True,
        "testing_suite": True,
        "stars": 969,
        "recency": "Active"
    },
    "binarcode-google-ads-mcp-http": {
        "repo": "BinarCode/google-ads-mcp-http",
        "desc": "Standalone HTTP and Streamable HTTP transport bridge for Google Ads MCP, built for containerized architectures and remote agents. Eliminates local stdio subprocess deadlocks when orchestrating pipelines in serverless or cloud environments.",
        "role": "Cloud Gateway",
        "runtime": "TypeScript",
        "transport": "Streamable HTTP",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "thainajardim-google-ads-mcp": {
        "repo": "ThainaJardim/google-ads-mcp",
        "desc": "Minimalist 3-tool reflection server that queries GoogleAdsFieldService dynamically at runtime, consuming only ~350 tokens per turn. Eliminates schema bloat by letting LLMs inspect available GAQL fields before constructing queries.",
        "role": "Schema Reflector",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": True,
        "offline_conversions": False,
        "gaql_reflection": True,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Ultra-Low (<500t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "davidmosiah-google-ads-mcp-unofficial": {
        "repo": "davidmosiah/google-ads-mcp-unofficial",
        "desc": "TypeScript reflection wrapper offering dynamic metadata inspection and consolidated reporting across active campaign entities. Designed for Cursor and Claude Desktop developers wanting zero-dependency Node installation.",
        "role": "Reporting Proxy",
        "runtime": "TypeScript",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": True,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 4,
        "recency": "Active"
    },
    "yeswanthreddyk-google-ads-mcp": {
        "repo": "yeswanthreddyk/Google-ads-MCP",
        "desc": "FastMCP Python server with 10 consolidated tools and Pydantic v2 schemas providing explicit type hints for LLM tool calling. Balances schema clarity with moderate token consumption across standard reporting endpoints.",
        "role": "FastMCP Proxy",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": True,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "cohnen-mcp-google-ads": {
        "repo": "cohnen/mcp-google-ads",
        "desc": "Community flagship with 710+ stars that completely bypasses the 500MB Python SDK in favor of direct requests.post REST calls. Serves official GAQL syntax references via gaql:// MCP resources for in-context query synthesis.",
        "role": "Lean REST Gateway",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": True,
        "offline_conversions": False,
        "gaql_reflection": True,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Ultra-Low (<500t)",
        "pre_ai_pedigree": True,
        "testing_suite": True,
        "stars": 710,
        "recency": "Active"
    },
    "x777-mcp-google-ads": {
        "repo": "x777/mcp-google-ads",
        "desc": "Python FastMCP server executing direct REST calls against Google Ads API v23 with 28 targeted tools. Uses Pydantic data modeling to serialize campaign and ad group metrics without SDK overhead.",
        "role": "FastMCP REST Proxy",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 1,
        "recency": "Active"
    },
    "afzalalisolangi-googleads-mcp-server": {
        "repo": "AfzalAliSolangi/GoogleAds-MCP-Server",
        "desc": "TypeScript MCP server optimized for Cloudflare Workers and edge execution with strict read-only guarantees. Implements streaming response parsing and web-standard OAuth token forwarding for serverless agents.",
        "role": "Edge Gateway",
        "runtime": "TypeScript",
        "transport": "stdio",
        "search_stream": True,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Ultra-Low (<500t)",
        "pre_ai_pedigree": True,
        "testing_suite": True,
        "stars": 0,
        "recency": "Active"
    },
    "minholi-google-ads-mcp": {
        "repo": "minholi/google-ads-mcp",
        "desc": "Compact Python proxy focusing on campaign-level KPI extraction and automated daily budget reporting. Returns sanitized Markdown summary tables directly formatted for LLM executive summaries.",
        "role": "Reporting Proxy",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 1,
        "recency": "Active"
    },
    "fgribreau-mcp-google-ads": {
        "repo": "FGRibreau/mcp-google-ads",
        "desc": "Compiled Rust MCP server delivering sub-millisecond execution times and minimal memory footprint (<15MB RSS). Ideal for high-concurrency enterprise microservices executing continuous GAQL search streams.",
        "role": "Native Rust Gateway",
        "runtime": "Rust",
        "transport": "stdio",
        "search_stream": True,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Ultra-Low (<500t)",
        "pre_ai_pedigree": True,
        "testing_suite": True,
        "stars": 52,
        "recency": "Active"
    },
    "lazare-42-google-ads-mcp": {
        "repo": "Lazare-42/google-ads-mcp",
        "desc": "High-performance Rust implementation with native Service Account authentication and automated Google OAuth token caching. Built for headless Docker agent containers requiring zero user interaction during execution.",
        "role": "Native Rust Proxy",
        "runtime": "Rust",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": True,
        "est_token_footprint": "Ultra-Low (<500t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "kiarashedraki-google-ads-mcp": {
        "repo": "kiarashedraki/google-ads-mcp",
        "desc": "TypeScript MCP implementation using environment refresh tokens and pre-compiled GAQL query templates. Targets modern JavaScript agent runtimes with minimal configuration overhead.",
        "role": "TypeScript Proxy",
        "runtime": "TypeScript",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "cristiandrei1234-google-ads-mcp": {
        "repo": "cristiandrei1234/google-ads-mcp",
        "desc": "TypeScript server wrapping core reporting services with structured zod validation schemas. Offers reliable reporting for campaigns, ad groups, and keyword performance in Node-based agent stacks.",
        "role": "TypeScript Proxy",
        "runtime": "TypeScript",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "klosk-adloop": {
        "repo": "kLOsk/adloop",
        "desc": "Pioneering Meta-MCP analytical engine running an embedded SQLite database in WAL mode with background worker synchronization. Executes complex multi-table SQL queries in 1.8ms–4.2ms with zero daily Google Ads API quota burn.",
        "role": "Meta-MCP Engine",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": True,
        "offline_conversions": False,
        "gaql_reflection": True,
        "sqlite_wal_cache": True,
        "query_latency": "Sub-5ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": True,
        "est_token_footprint": "Ultra-Low (<500t)",
        "pre_ai_pedigree": True,
        "testing_suite": True,
        "stars": 266,
        "recency": "Active"
    },
    "akelaonline-mcp-google-ads": {
        "repo": "akelaonline/MCP-Google-Ads",
        "desc": "Python local data warehouse server that synchronizes account structures into local SQLite tables upon initialization. Enables agents to run arbitrary SQL joins across campaigns, metrics, and bid strategies without latency.",
        "role": "Local SQLite Engine",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": True,
        "query_latency": "Sub-5ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": True,
        "testing_suite": True,
        "stars": 4,
        "recency": "Active"
    },
    "atlasbarinc-google-ads-mcp": {
        "repo": "atlasbarinc/google-ads-mcp",
        "desc": "Local analytical cache server designed for financial audit pipelines and historical metric comparison. Stores campaign snapshots on disk to support longitudinal performance reviews without hitting rate limits.",
        "role": "Analytical Cache",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": True,
        "query_latency": "Sub-5ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": True,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "mharnett-mcp-google-ads": {
        "repo": "mharnett/mcp-google-ads",
        "desc": "TypeScript caching server with 167 commits implementing SQLite persistence for ad performance and search query reports. Provides reliable offline query tools for local analysis in Claude Desktop.",
        "role": "Local Cache Proxy",
        "runtime": "TypeScript",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": True,
        "query_latency": "Sub-5ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 1,
        "recency": "Active"
    },
    "lucassantana-dev-google-ads-mcp": {
        "repo": "LucasSantana-Dev/google-ads-mcp",
        "desc": "Python reporting and caching implementation with built-in export utilities for tabular CSV and JSON analytics. Supports offline data exploration for PPC media buyers triaging underperforming keywords.",
        "role": "Analytical Proxy",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": True,
        "query_latency": "Sub-5ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 1,
        "recency": "Active"
    },
    "saifshabsug-google-ads-mcp-pro": {
        "repo": "saifshabsug/google-ads-mcp-pro",
        "desc": "Dedicated mutation server offering 43 write endpoints to pause campaigns, adjust daily budgets, and change keyword bids directly. Eliminates read-only passivity for agents acting as automated PPC bid managers.",
        "role": "Campaign Mutator",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 1,
        "recency": "Active"
    },
    "grantweston-google-ads-mcp-complete": {
        "repo": "grantweston/google-ads-mcp-complete",
        "desc": "Comprehensive multi-service wrapper exposing CampaignService, AdGroupService, and AdGroupCriterionService mutation tools. Built for automated bid adjustments, ad schedule updates, and negative keyword list synchronization.",
        "role": "Campaign Mutator",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": True,
        "testing_suite": False,
        "stars": 25,
        "recency": "Active"
    },
    "promobase-google-ads-mcp": {
        "repo": "promobase/google-ads-mcp",
        "desc": "Agency-focused mutation proxy allowing agents to update promotional budgets, toggle seasonal ad groups, and pause ad spend. Incorporates account ID validation to prevent cross-client budget pollution.",
        "role": "Budget Mutator",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": True,
        "testing_suite": False,
        "stars": 22,
        "recency": "Active"
    },
    "epave-google-ads-mcp": {
        "repo": "epave/google-ads-mcp",
        "desc": "Safety-first campaign CRUD server enforcing validate_only dry-run preflights on all mutate operations. Prevents invalid budget increments and malformed ad structures from throwing unrecoverable API errors.",
        "role": "Guarded Mutator",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": True,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "rgellis-google-ads-mcp": {
        "repo": "rgellis/google-ads-mcp",
        "desc": "Python mutation suite with 166 commits implementing transactional checks and rollback safeguards for campaign bid adjustments. Built to support robust agentic self-healing workflows.",
        "role": "Guarded Mutator",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": True,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "abdulrhmanalhur-google-ads-mcp": {
        "repo": "abdulrhmanalhur/google-ads-MCP",
        "desc": "Validated campaign management server checking currency micros conversions and bid limits before issuing Google Ads API calls. Protects against LLM decimal slips that could overspend budget.",
        "role": "Guarded Mutator",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": True,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": True,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "matheusslg-google-ads-mcp": {
        "repo": "matheusslg/google-ads-mcp",
        "desc": "Python server featuring atomic mutate handlers for updating campaign statuses and target ROAS settings. Includes pre-commit validation to ensure campaign budget IDs match target campaigns.",
        "role": "Guarded Mutator",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": True,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "konradbachowski-google-ads-mcp": {
        "repo": "konradbachowski/google-ads-mcp",
        "desc": "Specialized Keyword Planner MCP server exposing fine-grained tools for keyword generation, search volume forecasting, and RLSA audience targeting. Enables agents to discover high-intent keyword targets and forecast monthly spend.",
        "role": "Keyword Specialist",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "High (>5000t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 1,
        "recency": "Active"
    },
    "growmedevelopment-google-ads-mcp": {
        "repo": "growmedevelopment/google-ads-mcp",
        "desc": "PPC keyword and ad group management server with 96 commits providing tools to audit keyword match types and negative keyword conflicts. Ideal for automated hygiene audits in Search campaigns.",
        "role": "Keyword Specialist",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 1,
        "recency": "Active"
    },
    "ball2jh-google-ads-mcp": {
        "repo": "ball2jh/google-ads-mcp",
        "desc": "Keyword and campaign management toolkit designed to sync negative keyword lists across multiple Search ad groups. Prevents cross-campaign cannibalization through automated list application.",
        "role": "Keyword Specialist",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 1,
        "recency": "Active"
    },
    "nowork-studio-notfair-plugin": {
        "repo": "nowork-studio/notfair-plugin",
        "desc": "Benchmark-topping autonomous growth platform (⭐ 3,840) implementing @modelcontextprotocol/ext-apps with sandboxed React widgets. Physical Approve & Execute buttons trigger JSON-RPC commits via window.postMessage, completely bypassing LLM hallucinations during live spend commits.",
        "role": "MCP App Platform",
        "runtime": "TypeScript",
        "transport": "Streamable HTTP",
        "search_stream": False,
        "dry_run": True,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": True,
        "offline_conversions": True,
        "gaql_reflection": True,
        "sqlite_wal_cache": True,
        "query_latency": "Sub-5ms",
        "mcp_apps_ui": True,
        "hitl_approval": True,
        "mcc_hierarchy": True,
        "token_refresh_daemon": True,
        "est_token_footprint": "Ultra-Low (<500t)",
        "pre_ai_pedigree": True,
        "testing_suite": True,
        "stars": 3840,
        "recency": "Active"
    },
    "ameydabhade-google-ads-mcp": {
        "repo": "ameydabhade/google-ads-mcp",
        "desc": "TypeScript MCP server pioneering interactive chat components for Google Ads performance monitoring. Renders visual ROAS charts and campaign status toggle buttons directly within Claude Desktop and Cursor chat interfaces.",
        "role": "MCP App UI",
        "runtime": "TypeScript",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": True,
        "hitl_approval": True,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 1,
        "recency": "Active"
    },
    "monsieurgoodmood-google-ads-mcp-plus": {
        "repo": "monsieurgoodmood/google-ads-mcp-plus",
        "desc": "Mutation protection layer introducing visual spend sliders and daily budget confirmation dialogs. Prevents autonomous agents from modifying budgets beyond predefined safety thresholds without explicit human review.",
        "role": "Spend Protector",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": True,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": True,
        "hitl_approval": True,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 1,
        "recency": "Active"
    },
    "locomotive-agency-google-ads-mcp": {
        "repo": "locomotive-agency/google-ads-mcp",
        "desc": "Agency spend guardrail server enforcing maximum daily spend limits and client-specific approval workflows. Emits human-in-the-loop review prompts whenever proposed budget increases exceed 20%.",
        "role": "Spend Protector",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": True,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": True,
        "hitl_approval": True,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "noordevtech-googleads-mcp": {
        "repo": "noordevtech/GoogleAds-mcp",
        "desc": "High-scoring agency gateway (B+ / 76.8%) offering seamless MCC multi-account switching via dynamic login_customer_id header routing. Enables agents to inspect account hierarchies and execute queries across hundreds of child accounts in a single session.",
        "role": "MCC Agency Gateway",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": True,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": True,
        "offline_conversions": False,
        "gaql_reflection": True,
        "sqlite_wal_cache": True,
        "query_latency": "Sub-5ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": True,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": True,
        "testing_suite": True,
        "stars": 0,
        "recency": "Active"
    },
    "trueclicks-google-ads-mcp-js": {
        "repo": "TrueClicks/google-ads-mcp-js",
        "desc": "JavaScript MCP implementation from the TrueClicks PPC audit platform providing MCC account tree discovery and agency-wide quality scoring. Integrates proprietary account audit heuristics with standard Google Ads reporting.",
        "role": "Audit & MCC Proxy",
        "runtime": "JavaScript",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": True,
        "testing_suite": False,
        "stars": 50,
        "recency": "Active"
    },
    "connorcallison-google-ads-mcp": {
        "repo": "ConnorCallison/google-ads-mcp",
        "desc": "Python MCC routing proxy providing account enumeration and automated cross-client performance benchmarking. Formats agency roll-up reports with clear customer ID attribution.",
        "role": "MCC Proxy",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "gomarble-ai-google-ads-mcp-server": {
        "repo": "gomarble-ai/google-ads-mcp-server",
        "desc": "Enterprise-grade server (⭐ 144) solving the 60-minute Google OAuth session drop with a proactive background token refresh daemon. Critical for long-running autonomous workflows that span multiple hours of batch reporting.",
        "role": "Enterprise Daemon",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": True,
        "live_mutations": True,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": True,
        "offline_conversions": False,
        "gaql_reflection": True,
        "sqlite_wal_cache": True,
        "query_latency": "Sub-5ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": True,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": True,
        "testing_suite": True,
        "stars": 144,
        "recency": "Active"
    },
    "connorstearns-mcp-google-ads": {
        "repo": "connorstearns/mcp-google-ads",
        "desc": "Python server featuring 87 commits with persistent OAuth token storage and automated refresh handling across development sessions. Eliminates repeated browser re-authentication during daily agent coding.",
        "role": "Auth Daemon",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": True,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "johnoconnor0-google-ads-mcp": {
        "repo": "johnoconnor0/google-ads-mcp",
        "desc": "Python implementation with 29 commits wrapping Google OAuth2 token lifecycle management with encrypted credential storage. Ensures secure credential caching for desktop agents.",
        "role": "Auth Daemon",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": True,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 16,
        "recency": "Active"
    },
    "dhawalshah-google-ads-mcp": {
        "repo": "dhawalshah/google-ads-mcp",
        "desc": "Multi-tenant credential isolation server supporting distinct customer OAuth configurations stored securely in environment namespaces. Prevents accidental cross-tenant data leakage in agency environments.",
        "role": "Multi-Tenant Proxy",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 1,
        "recency": "Active"
    },
    "abhibavishi-google-ads-mcp": {
        "repo": "abhibavishi/google-ads-mcp",
        "desc": "Python agency gateway with 41 commits providing client account isolation and structured metric reporting. Includes safety checks to ensure queries target valid customer IDs.",
        "role": "Agency Proxy",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": True,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "shivpanks19-mcp-google-ads": {
        "repo": "shivpanks19/mcp-google-ads",
        "desc": "Python proxy supporting dynamic credential switching across multiple Google Cloud project client IDs. Suitable for consultancy teams managing disparate client infrastructure.",
        "role": "Agency Proxy",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "videngrowth-public-google-ads-mcp": {
        "repo": "VidenGrowth/public-google-ads-mcp",
        "desc": "Open agency connector from Viden Growth facilitating multi-account performance aggregation and automated client reporting. Tailored for agency media planners reviewing cross-client spend.",
        "role": "Agency Proxy",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 2,
        "recency": "Active"
    },
    "mathiaschu-google-ads-analyzer": {
        "repo": "mathiaschu/google-ads-analyzer",
        "desc": "Cognitive reasoning engine embodying 12 expert PPC domain playbooks. Programmatically discounts conversion metrics using 7-day conversion lag curves and applies Bid-to-Position heuristics before recommending budget changes.",
        "role": "Cognitive Brain",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": True,
        "offline_conversions": False,
        "gaql_reflection": True,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": True,
        "testing_suite": True,
        "stars": 67,
        "recency": "Active"
    },
    "brandonmiller18-google-ads-mcp": {
        "repo": "BrandonMiller18/google-ads-mcp",
        "desc": "Specialized analytics server calculating impression share lost to budget versus rank, converting currency micros to standard units ($1 = 1,000,000 micros). Protects agents from misinterpreting raw AdTech integers.",
        "role": "Analytics Helper",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 1,
        "recency": "Active"
    },
    "alexeykozyavkin-google-ads-mcp": {
        "repo": "alexeykozyavkin/google-ads-mcp",
        "desc": "Performance audit server providing automated calculation of click-through rate (CTR) anomalies and cost-per-click (CPC) trends across Search campaigns. Delivers clean tabular outputs for agent consumption.",
        "role": "Analytics Helper",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "codyp10-google-ads-mcp": {
        "repo": "Codyp10/Google-Ads-MCP",
        "desc": "Python analytics proxy formatting campaign metrics into concise executive summaries with automated currency conversions. Reduces token overhead by stripping raw nested API structures.",
        "role": "Analytics Helper",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "thatrebeccarae-claude-marketing": {
        "repo": "thatrebeccarae/claude-marketing",
        "desc": "Popular Claude Code skill collection (⭐ 147) integrating Google Ads audit routines directly into terminal-native agent workflows. Features pre-engineered prompts and scripts for analyzing Search campaign performance.",
        "role": "Claude Skill Pack",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": True,
        "testing_suite": False,
        "stars": 147,
        "recency": "Active"
    },
    "themattberman-google-ads-copilot": {
        "repo": "TheMattBerman/google-ads-copilot",
        "desc": "High-profile copilot repository (⭐ 235) orchestrating Docker containers and agentic scripts to monitor live ad accounts. Generates proactive Telegram and terminal alerts when budget pacing deviates from target thresholds.",
        "role": "Agentic Copilot",
        "runtime": "Shell",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": True,
        "testing_suite": False,
        "stars": 235,
        "recency": "Active"
    },
    "irinabuht12-oss-marketing-skills": {
        "repo": "irinabuht12-oss/marketing-skills",
        "desc": "Comprehensive marketing skill repository (⭐ 1,638) containing ready-to-run markdown skill instructions for Google Ads and paid media optimization. Teaches agents how to diagnose Quality Score drops and structure RSA copy.",
        "role": "Agent Skill Suite",
        "runtime": "Markdown",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": True,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 1638,
        "recency": "Active"
    },
    "irinabuht12-oss-google-meta-ads-ga4-mcp": {
        "repo": "irinabuht12-oss/google-meta-ads-ga4-mcp",
        "desc": "Massive multi-platform suite (⭐ 2,033) uniting Google Ads, Meta Ads, and Google Analytics 4 under a single MCP server. Enables cross-channel attribution queries and blended ROAS calculations within a unified agent context.",
        "role": "Multi-Platform Suite",
        "runtime": "Polyglot",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": True,
        "video_display": True,
        "offline_conversions": True,
        "gaql_reflection": True,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": True,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 2033,
        "recency": "Active"
    },
    "itallstartedwithaidea-google-ads-mcp": {
        "repo": "itallstartedwithaidea/google-ads-mcp",
        "desc": "Multi-channel marketing server bridging Google Ads performance data with Meta Ads and GA4 reporting pipelines. Built for performance marketers analyzing blended return on ad spend across paid media channels.",
        "role": "Marketing Bridge",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 3,
        "recency": "Active"
    },
    "iflow-mcp-itallstartedwithaidea-google-ads-mcp": {
        "repo": "iflow-mcp/itallstartedwithaidea-google-ads-mcp",
        "desc": "Active downstream fork maintaining cross-platform marketing tools with updated dependency pins and MCP specification compliance. Supports cross-channel reporting for Search and Social campaigns.",
        "role": "Marketing Bridge",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "zelentsov-dev-google-ads-mcp": {
        "repo": "zelentsov-dev/google-ads-mcp",
        "desc": "Marketing analytics server providing unified data extraction for Google Ads campaigns and Google Analytics 4 conversion events. Simplifies attribution reporting in agent workflows.",
        "role": "Analytics Bridge",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "huzaifa-hb-google-ads-mcp": {
        "repo": "huzaifa-hb/Google-Ads-MCP",
        "desc": "Python marketing proxy with 63 commits connecting Google Ads campaign telemetry with ecommerce store conversion tracking. Formats ROAS summaries for automated client updates.",
        "role": "Analytics Bridge",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    },
    "mailmanar-google-ads-mcp": {
        "repo": "mailmanar/google-ads-mcp",
        "desc": "Cross-channel reporting server with 66 commits providing consolidated spend tracking across Google Ads and supplementary advertising channels. Focuses on daily pacing alerts and budget anomaly detection.",
        "role": "Analytics Bridge",
        "runtime": "Python",
        "transport": "stdio",
        "search_stream": False,
        "dry_run": False,
        "live_mutations": False,
        "search_ads": True,
        "pmax_shopping": False,
        "video_display": False,
        "offline_conversions": False,
        "gaql_reflection": False,
        "sqlite_wal_cache": False,
        "query_latency": "800ms–2500ms",
        "mcp_apps_ui": False,
        "hitl_approval": False,
        "mcc_hierarchy": False,
        "token_refresh_daemon": False,
        "est_token_footprint": "Low (<1800t)",
        "pre_ai_pedigree": False,
        "testing_suite": False,
        "stars": 0,
        "recency": "Active"
    }
}

def main():
    registry = {
        "version": "1.0.0",
        "updated_at": "2026-09-21T19:15:00Z",
        "total_projects": len(tools_data),
        "categories": [],
        "projects": []
    }

    for cat in taxonomy_defs:
        cat_entry = {
            "id": cat["id"],
            "number": cat["number"],
            "name": cat["name"],
            "slug": cat["slug"],
            "description": cat["description"],
            "count": 0,
            "subcategories": []
        }
        cat_total = 0
        for sub in cat["subcategories"]:
            sub_count = len(sub["tool_slugs"])
            cat_total += sub_count
            sub_entry = {
                "name": sub["name"],
                "slug": sub["slug"],
                "description": sub["description"],
                "count": sub_count,
                "tool_slugs": sub["tool_slugs"]
            }
            cat_entry["subcategories"].append(sub_entry)
            
            for slug in sub["tool_slugs"]:
                td = tools_data[slug]
                p_entry = {
                    "slug": slug,
                    "repo": td["repo"],
                    "url": f"https://github.com/{td['repo']}",
                    "category_num": cat["number"],
                    "subcategory_slug": sub["slug"],
                    "description": td["desc"],
                    "role": td["role"],
                    "runtime": td["runtime"],
                    "transport": td["transport"],
                    "search_stream": td["search_stream"],
                    "dry_run": td["dry_run"],
                    "live_mutations": td["live_mutations"],
                    "search_ads": td["search_ads"],
                    "pmax_shopping": td["pmax_shopping"],
                    "video_display": td["video_display"],
                    "offline_conversions": td["offline_conversions"],
                    "gaql_reflection": td["gaql_reflection"],
                    "sqlite_wal_cache": td["sqlite_wal_cache"],
                    "query_latency": td["query_latency"],
                    "mcp_apps_ui": td["mcp_apps_ui"],
                    "hitl_approval": td["hitl_approval"],
                    "mcc_hierarchy": td["mcc_hierarchy"],
                    "token_refresh_daemon": td["token_refresh_daemon"],
                    "est_token_footprint": td["est_token_footprint"],
                    "pre_ai_pedigree": td["pre_ai_pedigree"],
                    "testing_suite": td["testing_suite"],
                    "stars": td["stars"],
                    "recency": td["recency"]
                }
                registry["projects"].append(p_entry)
                
        cat_entry["count"] = cat_total
        registry["categories"].append(cat_entry)

    # Validate against schema
    schema_path = os.path.join(DATA_DIR, "schema.json")
    with open(schema_path) as sf:
        schema = json.load(sf)
    
    jsonschema.validate(instance=registry, schema=schema)
    print("✓ registry.json passes schema validation!")

    registry_path = os.path.join(DATA_DIR, "registry.json")
    with open(registry_path, "w") as f:
        json.dump(registry, f, indent=2)
    print(f"✓ Written {len(registry['projects'])} projects to {registry_path}")

if __name__ == "__main__":
    main()
